### ISSUE TITLE
non-zero exit status 4294967295 when patching files

### ISSUE THREAD

**Issue by adamboy7** [thundrio-kh/khpc-modsmanager-bridge#2]
Game: KH2
Mode: Patch
Region: US
Game version: 1.0.0.7 freshly installed from epic games
Seed: https://kh2-randomizer.herokuapp.com/seed/FUHWEAMF
Additional mods: KH2FM-Mods-Num/GoA-ROM-Edition 

```
Replacing original: map/hb26.map!

FATAL ERROR: Something is wrong here!
   at OpenKh.Egs.EgsTools.ReplaceRemasteredAssets(String inputFolder, String originalFile, EgsHdAsset asset, FileStream pkgStream, Byte[] seed, Byte[] originalAssetData)

   at OpenKh.Egs.EgsTools.ReplaceFile(String inputFolder, String filename, FileStream hedStream, FileStream pkgStream, EgsHdAsset asset, Entry originalHedHeader)

   at OpenKh.Egs.EgsTools.Patch(String pkgFile, String inputFolder, String outputFolder)

   at OpenKh.Command.IdxImg.Program.EpicGamesAssets.PatchCommand.OnExecute(CommandLineApplication app)

--- End of stack trace from previous location ---

   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)

   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)

   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)

   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)

   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)

   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)

   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)

   at OpenKh.Command.IdxImg.Program.Main(String[] args)

Traceback (most recent call last):
  File "build_from_mm.py", line 306, in main
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['D:\\mod-manager\\openkh\\OpenKh.Command.IdxImg.exe', 'hed', 'patch', 'D:\\Games\\KH_1.5_2.5\\Image\\en\\kh2_fifth.pkg', 'khbuild\\kh2_fifth', '-o', 'pkgoutput']' returned non-zero exit status 4294967295.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_from_mm.py", line 319, in <module>
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
  File "build_from_mm.py", line 311, in main
Exception: Patch failed
[1752] Failed to execute script 'build_from_mm' due to unhandled exception!

```

**Comment by adamboy7** [comment]
Found the issue, the backup of my packages weren't unmodified. Verify your install using epic games or reinstall, fixed my issue.
